language: cpp

sudo: false

# gcc fails to configure. I don't know why.
compiler:
  - clang

script: ./autosetup.sh && ./configure && make

notifications:
  irc: "irc.freenode.org#spearmint"
  on_success: change
  on_failure: always

addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - qtbase5-dev
    - qtbase5-dev-tools
    - qttools5-dev-tools
    - libqt5opengl5-dev
    - libhtml-template-perl

